### ISSUE TITLE
Program exiting instead of going back.

### ISSUE THREAD

**Issue by avi465** [devXprite/infoooze#15]
### Describe the bug
I noticed that the option no. "1, 2, 7, 14, 15" dosen't ask to back, rather program exit execution.
i am taking about the options we get by running "infooze".
see the below screenshot.

**Suggestion**
I think it is bad to have banner animation every time we go back. I think animation should show up on first load only.

### Screenshots
<img width="631" alt="Screenshot 2022-07-18 222831" src="https://user-images.githubusercontent.com/63386918/179564270-3bd13336-b84a-441c-9ded-ae21251929f6.png">

here for example option no 7, after execution instead of going back it exits.

### System Information

**Infoooze Version** : 1.1.9
**Node Version** : v16.13.2
**OS Type** : Linux
**OS Version** : 5.10.60.1-microsoft-standard-WSL2
**OS Plateform** : linux

**Comment by devXprite** [comment]
Thank You @avi465 for reporting this bug. I have fixed this bug in PR #16. I have also reduced that banner animation time from _**1.5sec**_ to _**300ms**_ which is almost none.
